language: php
php:
  - 5.4

branches:
  only:
    - master

before_install:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-source --no-interaction

script: phpunit  -c phpunit.travis.xml

notifications:
  irc: "irc.freenode.org#webforge"
  mail: p.scheit@ps-webforge.com